'use client'
import {useEffect} from "react";
import { TestMsisdn } from "../../type";

let msisdn: TestMsisdn[] = [
    {code:'BEN',country:'Benin',mno:'MTN_MOMO_BEN',paymentType: 'DEPOSIT',msisdn:'22951345029',failureReason:'PAYER_NOT_FOUND'},
    {code:'BEN',country:'Benin',mno:'MTN_MOMO_BEN',paymentType: 'DEPOSIT',msisdn:'22951345039',failureReason:'PAYMENT_NOT_APPROVED'},
    {code:'BEN',country:'Benin',mno:'MTN_MOMO_BEN',paymentType: 'DEPOSIT',msisdn:'22951345069',failureReason:'OTHER_ERROR'},
    {code:'BEN',country:'Benin',mno:'MTN_MOMO_BEN',paymentType: 'DEPOSIT',msisdn:'22951345129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'BEN',country:'Benin',mno:'MTN_MOMO_BEN',paymentType: 'DEPOSIT',msisdn:'22951345789',failureReason:'SUCCESS'},
    {code:'BEN',country:'Benin',mno:'MTN_MOMO_BEN',paymentType:'PAYOUT',msisdn:'22951345089',failureReason:'RECIPIENT_NOT_FOUND'},
    {code:'BEN',country:'Benin',mno:'MTN_MOMO_BEN',paymentType:'PAYOUT',msisdn:'22951345119',failureReason:'OTHER_ERROR'},
    {code:'BEN',country:'Benin',mno:'MTN_MOMO_BEN',paymentType:'PAYOUT',msisdn:'22951345129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'BEN',country:'Benin',mno:'MTN_MOMO_BEN',paymentType:'PAYOUT',msisdn:'22951345789',failureReason:'SUCCESS'},
    {code:'BEN',country:'Benin',mno:'MOOV_BEN',paymentType: 'DEPOSIT',msisdn:'22995345679',failureReason:'PAYMENT_NOT_APPROVED'},
    {code:'BEN',country:'Benin',mno:'MOOV_BEN',paymentType: 'DEPOSIT',msisdn:'22995345529',failureReason:'OTHER_ERROR'},
    {code:'BEN',country:'Benin',mno:'MOOV_BEN',paymentType: 'DEPOSIT',msisdn:'22995345639',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'BEN',country:'Benin',mno:'MOOV_BEN',paymentType: 'DEPOSIT',msisdn:'22995345789',failureReason:'SUCCESS'},
    {code:'BEN',country:'Benin',mno:'MOOV_BEN',paymentType:'PAYOUT',msisdn:'22995345219',failureReason:'OTHER_ERROR'},
    {code:'BEN',country:'Benin',mno:'MOOV_BEN',paymentType:'PAYOUT',msisdn:'22995345279',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'BEN',country:'Benin',mno:'MOOV_BEN',paymentType:'PAYOUT',msisdn:'22995345789',failureReason:'SUCCESS'},
    {code:'CMR',country:'Cameroon',mno:'MTN_MOMO_CMR',paymentType: 'DEPOSIT',msisdn:'237653456019',failureReason:'PAYER_LIMIT_REACHED'},
    {code:'CMR',country:'Cameroon',mno:'MTN_MOMO_CMR',paymentType: 'DEPOSIT',msisdn:'237653456029',failureReason:'PAYER_NOT_FOUND'},
    {code:'CMR',country:'Cameroon',mno:'MTN_MOMO_CMR',paymentType: 'DEPOSIT',msisdn:'237653456039',failureReason:'PAYMENT_NOT_APPROVED'},
    {code:'CMR',country:'Cameroon',mno:'MTN_MOMO_CMR',paymentType: 'DEPOSIT',msisdn:'237653456069',failureReason:'OTHER_ERROR'},
    {code:'CMR',country:'Cameroon',mno:'MTN_MOMO_CMR',paymentType: 'DEPOSIT',msisdn:'237653456129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'CMR',country:'Cameroon',mno:'MTN_MOMO_CMR',paymentType: 'DEPOSIT',msisdn:'237653456789',failureReason:'SUCCESS'},
    {code:'CMR',country:'Cameroon',mno:'MTN_MOMO_CMR',paymentType:'PAYOUT',msisdn:'237653456089',failureReason:'RECIPIENT_NOT_FOUND'},
    {code:'CMR',country:'Cameroon',mno:'MTN_MOMO_CMR',paymentType:'PAYOUT',msisdn:'237653456119',failureReason:'OTHER_ERROR'},
    {code:'CMR',country:'Cameroon',mno:'MTN_MOMO_CMR',paymentType:'PAYOUT',msisdn:'237653456129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'CMR',country:'Cameroon',mno:'MTN_MOMO_CMR',paymentType:'PAYOUT',msisdn:'237653456789',failureReason:'SUCCESS'},
    {code:'CMR',country:'Cameroon',mno:'ORANGE_CMR',paymentType: 'DEPOSIT',msisdn:'237693456019',failureReason:'PAYER_LIMIT_REACHED'},
    {code:'CMR',country:'Cameroon',mno:'ORANGE_CMR',paymentType: 'DEPOSIT',msisdn:'237693456029',failureReason:'PAYER_NOT_FOUND'},
    {code:'CMR',country:'Cameroon',mno:'ORANGE_CMR',paymentType: 'DEPOSIT',msisdn:'237693456039',failureReason:'PAYMENT_NOT_APPROVED'},
    {code:'CMR',country:'Cameroon',mno:'ORANGE_CMR',paymentType: 'DEPOSIT',msisdn:'237693456049',failureReason:'INSUFFICIENT_BALANCE'},
    {code:'CMR',country:'Cameroon',mno:'ORANGE_CMR',paymentType: 'DEPOSIT',msisdn:'237693456069',failureReason:'OTHER_ERROR'},
    {code:'CMR',country:'Cameroon',mno:'ORANGE_CMR',paymentType: 'DEPOSIT',msisdn:'237693456129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'CMR',country:'Cameroon',mno:'ORANGE_CMR',paymentType: 'DEPOSIT',msisdn:'237693456789',failureReason:'SUCCESS'},
    {code:'CMR',country:'Cameroon',mno:'ORANGE_CMR',paymentType:'PAYOUT',msisdn:'237693456099',failureReason:'RECIPIENT_NOT_ALLOWED_TO_RECEIVE'},
    {code:'CMR',country:'Cameroon',mno:'ORANGE_CMR',paymentType:'PAYOUT',msisdn:'237693456119',failureReason:'OTHER_ERROR'},
    {code:'CMR',country:'Cameroon',mno:'ORANGE_CMR',paymentType:'PAYOUT',msisdn:'237693456129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'CMR',country:'Cameroon',mno:'ORANGE_CMR',paymentType:'PAYOUT',msisdn:'237693456789',failureReason:'SUCCESS'},
    {code:'CIV',country:`Côte d'Ivoire`,mno:'MTN_MOMO_CIV',paymentType: 'DEPOSIT',msisdn:'2250503456029',failureReason:'PAYER_NOT_FOUND'},
    {code:'CIV',country:`Côte d'Ivoire`,mno:'MTN_MOMO_CIV',paymentType: 'DEPOSIT',msisdn:'2250503456039',failureReason:'PAYMENT_NOT_APPROVED'},
    {code:'CIV',country:`Côte d'Ivoire`,mno:'MTN_MOMO_CIV',paymentType: 'DEPOSIT',msisdn:'2250503456069',failureReason:'OTHER_ERROR'},
    {code:'CIV',country:`Côte d'Ivoire`,mno:'MTN_MOMO_CIV',paymentType: 'DEPOSIT',msisdn:'2250503456129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'CIV',country:`Côte d'Ivoire`,mno:'MTN_MOMO_CIV',paymentType: 'DEPOSIT',msisdn:'2250503456789',failureReason:'SUCCESS'},
    {code:'CIV',country:`Côte d'Ivoire`,mno:'MTN_MOMO_CIV',paymentType:'PAYOUT',msisdn:'2250503456089',failureReason:'RECIPIENT_NOT_FOUND'},
    {code:'CIV',country:`Côte d'Ivoire`,mno:'MTN_MOMO_CIV',paymentType:'PAYOUT',msisdn:'2250503456119',failureReason:'OTHER_ERROR'},
    {code:'CIV',country:`Côte d'Ivoire`,mno:'MTN_MOMO_CIV',paymentType:'PAYOUT',msisdn:'2250503456129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'CIV',country:`Côte d'Ivoire`,mno:'MTN_MOMO_CIV',paymentType:'PAYOUT',msisdn:'2250503456789',failureReason:'SUCCESS'},
    {code:'COD',country:'Democratic Republic of the Congo',mno:'VODACOM_MPESA_COD',paymentType: 'DEPOSIT',msisdn:'243813456019',failureReason:'PAYER_LIMIT_REACHED'},
    {code:'COD',country:'Democratic Republic of the Congo',mno:'VODACOM_MPESA_COD',paymentType: 'DEPOSIT',msisdn:'243813456029',failureReason:'PAYER_NOT_FOUND'},
    {code:'COD',country:'Democratic Republic of the Congo',mno:'VODACOM_MPESA_COD',paymentType: 'DEPOSIT',msisdn:'243813456039',failureReason:'PAYMENT_NOT_APPROVED'},
    {code:'COD',country:'Democratic Republic of the Congo',mno:'VODACOM_MPESA_COD',paymentType: 'DEPOSIT',msisdn:'243813456049',failureReason:'INSUFFICIENT_BALANCE'},
    {code:'COD',country:'Democratic Republic of the Congo',mno:'VODACOM_MPESA_COD',paymentType: 'DEPOSIT',msisdn:'243813456069',failureReason:'OTHER_ERROR'},
    {code:'COD',country:'Democratic Republic of the Congo',mno:'VODACOM_MPESA_COD',paymentType: 'DEPOSIT',msisdn:'243813456129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'COD',country:'Democratic Republic of the Congo',mno:'VODACOM_MPESA_COD',paymentType: 'DEPOSIT',msisdn:'243813456789',failureReason:'SUCCESS'},
    {code:'COD',country:'Democratic Republic of the Congo',mno:'VODACOM_MPESA_COD',paymentType:'PAYOUT',msisdn:'243813456089',failureReason:'RECIPIENT_NOT_FOUND'},
    {code:'COD',country:'Democratic Republic of the Congo',mno:'VODACOM_MPESA_COD',paymentType:'PAYOUT',msisdn:'243813456119',failureReason:'OTHER_ERROR'},
    {code:'COD',country:'Democratic Republic of the Congo',mno:'VODACOM_MPESA_COD',paymentType:'PAYOUT',msisdn:'243813456129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'COD',country:'Democratic Republic of the Congo',mno:'VODACOM_MPESA_COD',paymentType:'PAYOUT',msisdn:'243813456789',failureReason:'SUCCESS'},
    {code:'COD',country:'Democratic Republic of the Congo',mno:'AIRTEL_COD',paymentType: 'DEPOSIT',msisdn:'243973456069',failureReason:'OTHER_ERROR'},
    {code:'COD',country:'Democratic Republic of the Congo',mno:'AIRTEL_COD',paymentType: 'DEPOSIT',msisdn:'243973456129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'COD',country:'Democratic Republic of the Congo',mno:'AIRTEL_COD',paymentType: 'DEPOSIT',msisdn:'243973456789',failureReason:'SUCCESS'},
    {code:'COD',country:'Democratic Republic of the Congo',mno:'AIRTEL_COD',paymentType:'PAYOUT',msisdn:'243973456089',failureReason:'RECIPIENT_NOT_FOUND'},
    {code:'COD',country:'Democratic Republic of the Congo',mno:'AIRTEL_COD',paymentType:'PAYOUT',msisdn:'243973456119',failureReason:'OTHER_ERROR'},
    {code:'COD',country:'Democratic Republic of the Congo',mno:'AIRTEL_COD',paymentType:'PAYOUT',msisdn:'243973456129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'COD',country:'Democratic Republic of the Congo',mno:'AIRTEL_COD',paymentType:'PAYOUT',msisdn:'243973456789',failureReason:'SUCCESS'},
    {code:'COD',country:'Democratic Republic of the Congo',mno:'ORANGE_COD',paymentType: 'DEPOSIT',msisdn:'243893456029',failureReason:'PAYER_NOT_FOUND'},
    {code:'COD',country:'Democratic Republic of the Congo',mno:'ORANGE_COD',paymentType: 'DEPOSIT',msisdn:'243893456039',failureReason:'PAYMENT_NOT_APPROVED'},
    {code:'COD',country:'Democratic Republic of the Congo',mno:'ORANGE_COD',paymentType: 'DEPOSIT',msisdn:'243893456049',failureReason:'INSUFFICIENT_BALANCE'},
    {code:'COD',country:'Democratic Republic of the Congo',mno:'ORANGE_COD',paymentType: 'DEPOSIT',msisdn:'243893456069',failureReason:'OTHER_ERROR'},
    {code:'COD',country:'Democratic Republic of the Congo',mno:'ORANGE_COD',paymentType: 'DEPOSIT',msisdn:'243893456129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'COD',country:'Democratic Republic of the Congo',mno:'ORANGE_COD',paymentType: 'DEPOSIT',msisdn:'243893456789',failureReason:'SUCCESS'},
    {code:'COD',country:'Democratic Republic of the Congo',mno:'ORANGE_COD',paymentType:'PAYOUT',msisdn:'243893456119',failureReason:'OTHER_ERROR'},
    {code:'COD',country:'Democratic Republic of the Congo',mno:'ORANGE_COD',paymentType:'PAYOUT',msisdn:'243893456129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'COD',country:'Democratic Republic of the Congo',mno:'ORANGE_COD',paymentType:'PAYOUT',msisdn:'243893456789',failureReason:'SUCCESS'},
    {code:'GHA',country:'Ghana',mno:'MTN_MOMO_GHA',paymentType: 'DEPOSIT',msisdn:'233593456019',failureReason:'PAYER_LIMIT_REACHED'},
    {code:'GHA',country:'Ghana',mno:'MTN_MOMO_GHA',paymentType: 'DEPOSIT',msisdn:'233593456029',failureReason:'PAYER_NOT_FOUND'},
    {code:'GHA',country:'Ghana',mno:'MTN_MOMO_GHA',paymentType: 'DEPOSIT',msisdn:'233593456039',failureReason:'PAYMENT_NOT_APPROVED'},
    {code:'GHA',country:'Ghana',mno:'MTN_MOMO_GHA',paymentType: 'DEPOSIT',msisdn:'233593456069',failureReason:'OTHER_ERROR'},
    {code:'GHA',country:'Ghana',mno:'MTN_MOMO_GHA',paymentType: 'DEPOSIT',msisdn:'233593456129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'GHA',country:'Ghana',mno:'MTN_MOMO_GHA',paymentType: 'DEPOSIT',msisdn:'233593456789',failureReason:'SUCCESS'},
    {code:'GHA',country:'Ghana',mno:'MTN_MOMO_GHA',paymentType:'PAYOUT',msisdn:'233593456089',failureReason:'RECIPIENT_NOT_FOUND'},
    {code:'GHA',country:'Ghana',mno:'MTN_MOMO_GHA',paymentType:'PAYOUT',msisdn:'233593456119',failureReason:'OTHER_ERROR'},
    {code:'GHA',country:'Ghana',mno:'MTN_MOMO_GHA',paymentType:'PAYOUT',msisdn:'233593456129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'GHA',country:'Ghana',mno:'MTN_MOMO_GHA',paymentType:'PAYOUT',msisdn:'233593456789',failureReason:'SUCCESS'},
    {code:'GHA',country:'Ghana',mno:'AIRTELTIGO_GHA',paymentType: 'DEPOSIT',msisdn:'233273456069',failureReason:'OTHER_ERROR'},
    {code:'GHA',country:'Ghana',mno:'AIRTELTIGO_GHA',paymentType: 'DEPOSIT',msisdn:'233273456129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'GHA',country:'Ghana',mno:'AIRTELTIGO_GHA',paymentType: 'DEPOSIT',msisdn:'233273456789',failureReason:'SUCCESS'},
    {code:'GHA',country:'Ghana',mno:'AIRTELTIGO_GHA',paymentType:'PAYOUT',msisdn:'233273456089',failureReason:'RECIPIENT_NOT_FOUND'},
    {code:'GHA',country:'Ghana',mno:'AIRTELTIGO_GHA',paymentType:'PAYOUT',msisdn:'233273456099',failureReason:'RECIPIENT_NOT_ALLOWED_TO_RECEIVE'},
    {code:'GHA',country:'Ghana',mno:'AIRTELTIGO_GHA',paymentType:'PAYOUT',msisdn:'233273456119',failureReason:'OTHER_ERROR'},
    {code:'GHA',country:'Ghana',mno:'AIRTELTIGO_GHA',paymentType:'PAYOUT',msisdn:'233273456129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'GHA',country:'Ghana',mno:'AIRTELTIGO_GHA',paymentType:'PAYOUT',msisdn:'233273456789',failureReason:'SUCCESS'},
    {code:'GHA',country:'Ghana',mno:'VODAFONE_GHA',paymentType: 'DEPOSIT',msisdn:'233503456039',failureReason:'PAYMENT_NOT_APPROVED'},
    {code:'GHA',country:'Ghana',mno:'VODAFONE_GHA',paymentType: 'DEPOSIT',msisdn:'233503456049',failureReason:'INSUFFICIENT_BALANCE'},
    {code:'GHA',country:'Ghana',mno:'VODAFONE_GHA',paymentType: 'DEPOSIT',msisdn:'233503456069',failureReason:'OTHER_ERROR'},
    {code:'GHA',country:'Ghana',mno:'VODAFONE_GHA',paymentType: 'DEPOSIT',msisdn:'233503456129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'GHA',country:'Ghana',mno:'VODAFONE_GHA',paymentType: 'DEPOSIT',msisdn:'233503456789',failureReason:'SUCCESS'},
    {code:'GHA',country:'Ghana',mno:'VODAFONE_GHA',paymentType:'PAYOUT',msisdn:'233503456089',failureReason:'RECIPIENT_NOT_FOUND'},
    {code:'GHA',country:'Ghana',mno:'VODAFONE_GHA',paymentType:'PAYOUT',msisdn:'233503456099',failureReason:'RECIPIENT_NOT_ALLOWED_TO_RECEIVE'},
    {code:'GHA',country:'Ghana',mno:'VODAFONE_GHA',paymentType:'PAYOUT',msisdn:'233503456119',failureReason:'OTHER_ERROR'},
    {code:'GHA',country:'Ghana',mno:'VODAFONE_GHA',paymentType:'PAYOUT',msisdn:'233503456129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'GHA',country:'Ghana',mno:'VODAFONE_GHA',paymentType:'PAYOUT',msisdn:'233503456789',failureReason:'SUCCESS'},
    {code:'KEN',country:'Kenya',mno:'MPESA_KEN',paymentType: 'DEPOSIT',msisdn:'254703456019',failureReason:'PAYER_LIMIT_REACHED'},
    {code:'KEN',country:'Kenya',mno:'MPESA_KEN',paymentType: 'DEPOSIT',msisdn:'254703456039',failureReason:'PAYMENT_NOT_APPROVED'},
    {code:'KEN',country:'Kenya',mno:'MPESA_KEN',paymentType: 'DEPOSIT',msisdn:'254703456049',failureReason:'INSUFFICIENT_BALANCE'},
    {code:'KEN',country:'Kenya',mno:'MPESA_KEN',paymentType: 'DEPOSIT',msisdn:'254703456059',failureReason:'TRANSACTION_ALREADY_IN_PROCESS'},
    {code:'KEN',country:'Kenya',mno:'MPESA_KEN',paymentType: 'DEPOSIT',msisdn:'254703456069',failureReason:'OTHER_ERROR'},
    {code:'KEN',country:'Kenya',mno:'MPESA_KEN',paymentType: 'DEPOSIT',msisdn:'254703456129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'KEN',country:'Kenya',mno:'MPESA_KEN',paymentType: 'DEPOSIT',msisdn:'254703456789',failureReason:'SUCCESS'},
    {code:'KEN',country:'Kenya',mno:'MPESA_KEN',paymentType:'PAYOUT',msisdn:'254703456089',failureReason:'RECIPIENT_NOT_FOUND'},
    {code:'KEN',country:'Kenya',mno:'MPESA_KEN',paymentType:'PAYOUT',msisdn:'254703456099',failureReason:'RECIPIENT_NOT_ALLOWED_TO_RECEIVE'},
    {code:'KEN',country:'Kenya',mno:'MPESA_KEN',paymentType:'PAYOUT',msisdn:'254703456109',failureReason:'RECIPIENT_LIMIT_REACHED'},
    {code:'KEN',country:'Kenya',mno:'MPESA_KEN',paymentType:'PAYOUT',msisdn:'254703456119',failureReason:'OTHER_ERROR'},
    {code:'KEN',country:'Kenya',mno:'MPESA_KEN',paymentType:'PAYOUT',msisdn:'254703456129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'KEN',country:'Kenya',mno:'MPESA_KEN',paymentType:'PAYOUT',msisdn:'254703456789',failureReason:'SUCCESS'},
    {code:'MWI',country:'Malawi',mno:'AIRTEL_MWI',paymentType: 'DEPOSIT',msisdn:'265993456049',failureReason:'INSUFFICIENT_BALANCE'},
    {code:'MWI',country:'Malawi',mno:'AIRTEL_MWI',paymentType: 'DEPOSIT',msisdn:'265993456069',failureReason:'OTHER_ERROR'},
    {code:'MWI',country:'Malawi',mno:'AIRTEL_MWI',paymentType: 'DEPOSIT',msisdn:'265993456129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'MWI',country:'Malawi',mno:'AIRTEL_MWI',paymentType: 'DEPOSIT',msisdn:'265993456789',failureReason:'SUCCESS'},
    {code:'MWI',country:'Malawi',mno:'AIRTEL_MWI',paymentType:'PAYOUT',msisdn:'265993456089',failureReason:'RECIPIENT_NOT_FOUND'},
    {code:'MWI',country:'Malawi',mno:'AIRTEL_MWI',paymentType:'PAYOUT',msisdn:'265993456119',failureReason:'OTHER_ERROR'},
    {code:'MWI',country:'Malawi',mno:'AIRTEL_MWI',paymentType:'PAYOUT',msisdn:'265993456129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'MWI',country:'Malawi',mno:'AIRTEL_MWI',paymentType:'PAYOUT',msisdn:'265993456789',failureReason:'SUCCESS'},
    {code:'MWI',country:'Malawi',mno:'TNM_MWI',paymentType: 'DEPOSIT',msisdn:'265883456049',failureReason:'INSUFFICIENT_BALANCE'},
    {code:'MWI',country:'Malawi',mno:'TNM_MWI',paymentType: 'DEPOSIT',msisdn:'265883456069',failureReason:'OTHER_ERROR'},
    {code:'MWI',country:'Malawi',mno:'TNM_MWI',paymentType: 'DEPOSIT',msisdn:'265883456129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'MWI',country:'Malawi',mno:'TNM_MWI',paymentType: 'DEPOSIT',msisdn:'265883456789',failureReason:'SUCCESS'},
    {code:'MWI',country:'Malawi',mno:'TNM_MWI',paymentType:'PAYOUT',msisdn:'265883456089',failureReason:'RECIPIENT_NOT_FOUND'},
    {code:'MWI',country:'Malawi',mno:'TNM_MWI',paymentType:'PAYOUT',msisdn:'265883456119',failureReason:'OTHER_ERROR'},
    {code:'MWI',country:'Malawi',mno:'TNM_MWI',paymentType:'PAYOUT',msisdn:'265883456129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'MWI',country:'Malawi',mno:'TNM_MWI',paymentType:'PAYOUT',msisdn:'265883456789',failureReason:'SUCCESS'},
    {code:'NGA',country:'Nigeria',mno:'AIRTEL_NGA',paymentType: 'DEPOSIT',msisdn:'2349034567069',failureReason:'OTHER_ERROR'},
    {code:'NGA',country:'Nigeria',mno:'AIRTEL_NGA',paymentType: 'DEPOSIT',msisdn:'2349034567129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'NGA',country:'Nigeria',mno:'AIRTEL_NGA',paymentType: 'DEPOSIT',msisdn:'2349034567899',failureReason:'SUCCESS'},
    {code:'NGA',country:'Nigeria',mno:'AIRTEL_NGA',paymentType: 'DEPOSIT',msisdn:'',failureReason:''},
    {code:'NGA',country:'Nigeria',mno:'AIRTEL_NGA',paymentType:'PAYOUT',msisdn:'2349034567089',failureReason:'RECIPIENT_NOT_FOUND'},
    {code:'NGA',country:'Nigeria',mno:'AIRTEL_NGA',paymentType:'PAYOUT',msisdn:'2349034567119',failureReason:'OTHER_ERROR'},
    {code:'NGA',country:'Nigeria',mno:'AIRTEL_NGA',paymentType:'PAYOUT',msisdn:'2349034567129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'NGA',country:'Nigeria',mno:'AIRTEL_NGA',paymentType:'PAYOUT',msisdn:'2349034567899',failureReason:'SUCCESS'},
    {code:'NGA',country:'Nigeria',mno:'MTN_MOMO_NGA',paymentType: 'DEPOSIT',msisdn:'2348134567019',failureReason:'PAYER_LIMIT_REACHED'},
    {code:'NGA',country:'Nigeria',mno:'MTN_MOMO_NGA',paymentType: 'DEPOSIT',msisdn:'2348134567029',failureReason:'PAYER_NOT_FOUND'},
    {code:'NGA',country:'Nigeria',mno:'MTN_MOMO_NGA',paymentType: 'DEPOSIT',msisdn:'2348134567039',failureReason:'PAYMENT_NOT_APPROVED'},
    {code:'NGA',country:'Nigeria',mno:'MTN_MOMO_NGA',paymentType: 'DEPOSIT',msisdn:'2348134567069',failureReason:'OTHER_ERROR'},
    {code:'NGA',country:'Nigeria',mno:'MTN_MOMO_NGA',paymentType: 'DEPOSIT',msisdn:'2348134567129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'NGA',country:'Nigeria',mno:'MTN_MOMO_NGA',paymentType: 'DEPOSIT',msisdn:'2348134567899',failureReason:'SUCCESS'},
    {code:'NGA',country:'Nigeria',mno:'MTN_MOMO_NGA',paymentType:'PAYOUT',msisdn:'2348134567089',failureReason:'RECIPIENT_NOT_FOUND'},
    {code:'NGA',country:'Nigeria',mno:'MTN_MOMO_NGA',paymentType:'PAYOUT',msisdn:'2348134567099',failureReason:'RECIPIENT_NOT_ALLOWED_TO_RECEIVE'},
    {code:'NGA',country:'Nigeria',mno:'MTN_MOMO_NGA',paymentType:'PAYOUT',msisdn:'2348134567119',failureReason:'OTHER_ERROR'},
    {code:'NGA',country:'Nigeria',mno:'MTN_MOMO_NGA',paymentType:'PAYOUT',msisdn:'2348134567129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'NGA',country:'Nigeria',mno:'MTN_MOMO_NGA',paymentType:'PAYOUT',msisdn:'2348134567899',failureReason:'SUCCESS'},
    {code:'RWA',country:'Rwanda',mno:'AIRTEL_RWA',paymentType: 'DEPOSIT',msisdn:'250733456039',failureReason:'PAYMENT_NOT_APPROVED'},
    {code:'RWA',country:'Rwanda',mno:'AIRTEL_RWA',paymentType: 'DEPOSIT',msisdn:'250733456049',failureReason:'INSUFFICIENT_BALANCE'},
    {code:'RWA',country:'Rwanda',mno:'AIRTEL_RWA',paymentType: 'DEPOSIT',msisdn:'250733456069',failureReason:'OTHER_ERROR'},
    {code:'RWA',country:'Rwanda',mno:'AIRTEL_RWA',paymentType: 'DEPOSIT',msisdn:'250733456129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'RWA',country:'Rwanda',mno:'AIRTEL_RWA',paymentType: 'DEPOSIT',msisdn:'250733456789',failureReason:'SUCCESS'},
    {code:'RWA',country:'Rwanda',mno:'AIRTEL_RWA',paymentType:'PAYOUT',msisdn:'250733456089',failureReason:'RECIPIENT_NOT_FOUND'},
    {code:'RWA',country:'Rwanda',mno:'AIRTEL_RWA',paymentType:'PAYOUT',msisdn:'250733456119',failureReason:'OTHER_ERROR'},
    {code:'RWA',country:'Rwanda',mno:'AIRTEL_RWA',paymentType:'PAYOUT',msisdn:'250733456129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'RWA',country:'Rwanda',mno:'AIRTEL_RWA',paymentType:'PAYOUT',msisdn:'250733456789',failureReason:'SUCCESS'},
    {code:'RWA',country:'Rwanda',mno:'MTN_MOMO_RWA',paymentType: 'DEPOSIT',msisdn:'250783456019',failureReason:'PAYER_LIMIT_REACHED'},
    {code:'RWA',country:'Rwanda',mno:'MTN_MOMO_RWA',paymentType: 'DEPOSIT',msisdn:'250783456029',failureReason:'PAYER_NOT_FOUND'},
    {code:'RWA',country:'Rwanda',mno:'MTN_MOMO_RWA',paymentType: 'DEPOSIT',msisdn:'250783456039',failureReason:'PAYMENT_NOT_APPROVED'},
    {code:'RWA',country:'Rwanda',mno:'MTN_MOMO_RWA',paymentType: 'DEPOSIT',msisdn:'250783456069',failureReason:'OTHER_ERROR'},
    {code:'RWA',country:'Rwanda',mno:'MTN_MOMO_RWA',paymentType: 'DEPOSIT',msisdn:'250783456129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'RWA',country:'Rwanda',mno:'MTN_MOMO_RWA',paymentType: 'DEPOSIT',msisdn:'250783456789',failureReason:'SUCCESS'},
    {code:'RWA',country:'Rwanda',mno:'MTN_MOMO_RWA',paymentType:'PAYOUT',msisdn:'250783456089',failureReason:'RECIPIENT_NOT_FOUND'},
    {code:'RWA',country:'Rwanda',mno:'MTN_MOMO_RWA',paymentType:'PAYOUT',msisdn:'250783456099',failureReason:'RECIPIENT_NOT_ALLOWED_TO_RECEIVE'},
    {code:'RWA',country:'Rwanda',mno:'MTN_MOMO_RWA',paymentType:'PAYOUT',msisdn:'250783456119',failureReason:'OTHER_ERROR'},
    {code:'RWA',country:'Rwanda',mno:'MTN_MOMO_RWA',paymentType:'PAYOUT',msisdn:'250783456129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'RWA',country:'Rwanda',mno:'MTN_MOMO_RWA',paymentType:'PAYOUT',msisdn:'250783456789',failureReason:'SUCCESS'},
    {code:'SEN',country:'Senegal',mno:'FREE_SEN',paymentType: 'DEPOSIT',msisdn:'221763456049',failureReason:'INSUFFICIENT_BALANCE'},
    {code:'SEN',country:'Senegal',mno:'FREE_SEN',paymentType: 'DEPOSIT',msisdn:'221763456069',failureReason:'OTHER_ERROR'},
    {code:'SEN',country:'Senegal',mno:'FREE_SEN',paymentType: 'DEPOSIT',msisdn:'221763456129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'SEN',country:'Senegal',mno:'FREE_SEN',paymentType: 'DEPOSIT',msisdn:'221763456789',failureReason:'SUCCESS'},
    {code:'SEN',country:'Senegal',mno:'FREE_SEN',paymentType:'PAYOUT',msisdn:'221763456119',failureReason:'OTHER_ERROR'},
    {code:'SEN',country:'Senegal',mno:'FREE_SEN',paymentType:'PAYOUT',msisdn:'221763456129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'SEN',country:'Senegal',mno:'FREE_SEN',paymentType:'PAYOUT',msisdn:'221763456789',failureReason:'SUCCESS'},
    {code:'SEN',country:'Senegal',mno:'ORANGE_SEN',paymentType: 'DEPOSIT',msisdn:'221773456029',failureReason:'PAYER_NOT_FOUND'},
    {code:'SEN',country:'Senegal',mno:'ORANGE_SEN',paymentType: 'DEPOSIT',msisdn:'221773456049',failureReason:'INSUFFICIENT_BALANCE'},
    {code:'SEN',country:'Senegal',mno:'ORANGE_SEN',paymentType: 'DEPOSIT',msisdn:'221773456069',failureReason:'OTHER_ERROR'},
    {code:'SEN',country:'Senegal',mno:'ORANGE_SEN',paymentType: 'DEPOSIT',msisdn:'221773456129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'SEN',country:'Senegal',mno:'ORANGE_SEN',paymentType: 'DEPOSIT',msisdn:'221773456789',failureReason:'SUCCESS'},
    {code:'SEN',country:'Senegal',mno:'ORANGE_SEN',paymentType:'PAYOUT',msisdn:'221773456119',failureReason:'OTHER_ERROR'},
    {code:'SEN',country:'Senegal',mno:'ORANGE_SEN',paymentType:'PAYOUT',msisdn:'221773456139',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'SEN',country:'Senegal',mno:'ORANGE_SEN',paymentType:'PAYOUT',msisdn:'221773456789',failureReason:'SUCCESS'},
    {code:'SLE',country:'Sierra Leone',mno:'ORANGE_SLE',paymentType: 'DEPOSIT',msisdn:'23276123456',failureReason:'SUCCESS'},
    {code:'SLE',country:'Sierra Leone',mno:'ORANGE_SLE',paymentType:'PAYOUT',msisdn:'23276123456',failureReason:'SUCCESS'},
    {code:'TZA',country:'Tanzania',mno:'AIRTE_TZA',paymentType: 'DEPOSIT',msisdn:'255683456019',failureReason:'PAYER_LIMIT_REACHED'},
    {code:'TZA',country:'Tanzania',mno:'AIRTE_TZA',paymentType: 'DEPOSIT',msisdn:'255683456039',failureReason:'PAYMENT_NOT_APPROVED'},
    {code:'TZA',country:'Tanzania',mno:'AIRTE_TZA',paymentType: 'DEPOSIT',msisdn:'255683456049',failureReason:'INSUFFICIENT_BALANCE'},
    {code:'TZA',country:'Tanzania',mno:'AIRTE_TZA',paymentType: 'DEPOSIT',msisdn:'255683456069',failureReason:'OTHER_ERROR'},
    {code:'TZA',country:'Tanzania',mno:'AIRTE_TZA',paymentType: 'DEPOSIT',msisdn:'255683456129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'TZA',country:'Tanzania',mno:'AIRTE_TZA',paymentType: 'DEPOSIT',msisdn:'255683456789',failureReason:'SUCCESS'},
    {code:'TZA',country:'Tanzania',mno:'AIRTE_TZA',paymentType:'PAYOUT',msisdn:'255683456089',failureReason:'RECIPIENT_NOT_FOUND'},
    {code:'TZA',country:'Tanzania',mno:'AIRTE_TZA',paymentType:'PAYOUT',msisdn:'255683456119',failureReason:'OTHER_ERROR'},
    {code:'TZA',country:'Tanzania',mno:'AIRTE_TZA',paymentType:'PAYOUT',msisdn:'255683456129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'TZA',country:'Tanzania',mno:'AIRTE_TZA',paymentType:'PAYOUT',msisdn:'255683456789',failureReason:'SUCCESS'},
    {code:'TZA',country:'Tanzania',mno:'VODACOM_TZA',paymentType: 'DEPOSIT',msisdn:'255763456039',failureReason:'PAYMENT_NOT_APPROVED'},
    {code:'TZA',country:'Tanzania',mno:'VODACOM_TZA',paymentType: 'DEPOSIT',msisdn:'255763456069',failureReason:'OTHER_ERROR'},
    {code:'TZA',country:'Tanzania',mno:'VODACOM_TZA',paymentType: 'DEPOSIT',msisdn:'255763456129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'TZA',country:'Tanzania',mno:'VODACOM_TZA',paymentType: 'DEPOSIT',msisdn:'255763456789',failureReason:'SUCCESS'},
    {code:'TZA',country:'Tanzania',mno:'VODACOM_TZA',paymentType:'PAYOUT',msisdn:'255763456119',failureReason:'OTHER_ERROR'},
    {code:'TZA',country:'Tanzania',mno:'VODACOM_TZA',paymentType:'PAYOUT',msisdn:'255763456129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'TZA',country:'Tanzania',mno:'VODACOM_TZA',paymentType:'PAYOUT',msisdn:'255763456789',failureReason:'SUCCESS'},
    {code:'TZA',country:'Tanzania',mno:'TIGO_TZA',paymentType: 'DEPOSIT',msisdn:'255713456039',failureReason:'PAYMENT_NOT_APPROVED'},
    {code:'TZA',country:'Tanzania',mno:'TIGO_TZA',paymentType: 'DEPOSIT',msisdn:'255713456049',failureReason:'INSUFFICIENT_BALANCE'},
    {code:'TZA',country:'Tanzania',mno:'TIGO_TZA',paymentType: 'DEPOSIT',msisdn:'255713456069',failureReason:'OTHER_ERROR'},
    {code:'TZA',country:'Tanzania',mno:'TIGO_TZA',paymentType: 'DEPOSIT',msisdn:'255713456129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'TZA',country:'Tanzania',mno:'TIGO_TZA',paymentType: 'DEPOSIT',msisdn:'255713456789',failureReason:'SUCCESS'},
    {code:'TZA',country:'Tanzania',mno:'TIGO_TZA',paymentType:'PAYOUT',msisdn:'255713456089',failureReason:'RECIPIENT_NOT_FOUND'},
    {code:'TZA',country:'Tanzania',mno:'TIGO_TZA',paymentType:'PAYOUT',msisdn:'255713456099',failureReason:'RECIPIENT_NOT_ALLOWED_TO_RECEIVE'},
    {code:'TZA',country:'Tanzania',mno:'TIGO_TZA',paymentType:'PAYOUT',msisdn:'255713456119',failureReason:'OTHER_ERROR'},
    {code:'TZA',country:'Tanzania',mno:'TIGO_TZA',paymentType:'PAYOUT',msisdn:'255713456129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'TZA',country:'Tanzania',mno:'TIGO_TZA',paymentType:'PAYOUT',msisdn:'255713456789',failureReason:'SUCCESS'},
    {code:'TZA',country:'Tanzania',mno:'HALOTEL_TZA',paymentType: 'DEPOSIT',msisdn:'255623456029',failureReason:'PAYER_NOT_FOUND'},
    {code:'TZA',country:'Tanzania',mno:'HALOTEL_TZA',paymentType: 'DEPOSIT',msisdn:'255623456049',failureReason:'INSUFFICIENT_BALANCE'},
    {code:'TZA',country:'Tanzania',mno:'HALOTEL_TZA',paymentType: 'DEPOSIT',msisdn:'255623456069',failureReason:'OTHER_ERROR'},
    {code:'TZA',country:'Tanzania',mno:'HALOTEL_TZA',paymentType: 'DEPOSIT',msisdn:'255623456129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'TZA',country:'Tanzania',mno:'HALOTEL_TZA',paymentType: 'DEPOSIT',msisdn:'255623456789',failureReason:'SUCCESS'},
    {code:'TZA',country:'Tanzania',mno:'HALOTEL_TZA',paymentType:'PAYOUT',msisdn:'255623456089',failureReason:'RECIPIENT_NOT_FOUND'},
    {code:'TZA',country:'Tanzania',mno:'HALOTEL_TZA',paymentType:'PAYOUT',msisdn:'255623456119',failureReason:'OTHER_ERROR'},
    {code:'TZA',country:'Tanzania',mno:'HALOTEL_TZA',paymentType:'PAYOUT',msisdn:'255623456129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'TZA',country:'Tanzania',mno:'HALOTEL_TZA',paymentType:'PAYOUT',msisdn:'255623456789',failureReason:'SUCCESS'},
    {code:'UGA',country:'Uganda',mno:'AIRTEL_OAPI_UGA',paymentType: 'DEPOSIT',msisdn:'256753456019',failureReason:'PAYER_LIMIT_REACHED'},
    {code:'UGA',country:'Uganda',mno:'AIRTEL_OAPI_UGA',paymentType: 'DEPOSIT',msisdn:'256753456039',failureReason:'PAYMENT_NOT_APPROVED'},
    {code:'UGA',country:'Uganda',mno:'AIRTEL_OAPI_UGA',paymentType: 'DEPOSIT',msisdn:'256753456049',failureReason:'INSUFFICIENT_BALANCE'},
    {code:'UGA',country:'Uganda',mno:'AIRTEL_OAPI_UGA',paymentType: 'DEPOSIT',msisdn:'256753456069',failureReason:'OTHER_ERROR'},
    {code:'UGA',country:'Uganda',mno:'AIRTEL_OAPI_UGA',paymentType: 'DEPOSIT',msisdn:'256753456129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'UGA',country:'Uganda',mno:'AIRTEL_OAPI_UGA',paymentType: 'DEPOSIT',msisdn:'256753456789',failureReason:'SUCCESS'},
    {code:'UGA',country:'Uganda',mno:'AIRTEL_OAPI_UGA',paymentType:'PAYOUT',msisdn:'256753456089',failureReason:'RECIPIENT_NOT_FOUND'},
    {code:'UGA',country:'Uganda',mno:'AIRTEL_OAPI_UGA',paymentType:'PAYOUT',msisdn:'256753456099',failureReason:'RECIPIENT_NOT_ALLOWED_TO_RECEIVE'},
    {code:'UGA',country:'Uganda',mno:'AIRTEL_OAPI_UGA',paymentType:'PAYOUT',msisdn:'256753456119',failureReason:'OTHER_ERROR'},
    {code:'UGA',country:'Uganda',mno:'AIRTEL_OAPI_UGA',paymentType:'PAYOUT',msisdn:'256753456129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'UGA',country:'Uganda',mno:'AIRTEL_OAPI_UGA',paymentType:'PAYOUT',msisdn:'256753456789',failureReason:'SUCCESS'},
    {code:'UGA',country:'Uganda',mno:'MTN_MOMO_UGA',paymentType: 'DEPOSIT',msisdn:'256783456019',failureReason:'PAYER_LIMIT_REACHED'},
    {code:'UGA',country:'Uganda',mno:'MTN_MOMO_UGA',paymentType: 'DEPOSIT',msisdn:'256783456029',failureReason:'PAYER_NOT_FOUND'},
    {code:'UGA',country:'Uganda',mno:'MTN_MOMO_UGA',paymentType: 'DEPOSIT',msisdn:'256783456069',failureReason:'OTHER_ERROR'},
    {code:'UGA',country:'Uganda',mno:'MTN_MOMO_UGA',paymentType: 'DEPOSIT',msisdn:'256783456129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'UGA',country:'Uganda',mno:'MTN_MOMO_UGA',paymentType: 'DEPOSIT',msisdn:'256783456789',failureReason:'SUCCESS'},
    {code:'UGA',country:'Uganda',mno:'MTN_MOMO_UGA',paymentType:'PAYOUT',msisdn:'256783456089',failureReason:'RECIPIENT_NOT_FOUND'},
    {code:'UGA',country:'Uganda',mno:'MTN_MOMO_UGA',paymentType:'PAYOUT',msisdn:'256783456099',failureReason:'RECIPIENT_NOT_ALLOWED_TO_RECEIVE'},
    {code:'UGA',country:'Uganda',mno:'MTN_MOMO_UGA',paymentType:'PAYOUT',msisdn:'256783456119',failureReason:'OTHER_ERROR'},
    {code:'UGA',country:'Uganda',mno:'MTN_MOMO_UGA',paymentType:'PAYOUT',msisdn:'256783456789',failureReason:'SUCCESS'},
    {code:'ZMB',country:'Zambia',mno:'AIRTEL_OAPI_ZMB',paymentType: 'DEPOSIT',msisdn:'260973456019',failureReason:'PAYER_LIMIT_REACHED'},
    {code:'ZMB',country:'Zambia',mno:'AIRTEL_OAPI_ZMB',paymentType: 'DEPOSIT',msisdn:'260973456039',failureReason:'PAYMENT_NOT_APPROVED'},
    {code:'ZMB',country:'Zambia',mno:'AIRTEL_OAPI_ZMB',paymentType: 'DEPOSIT',msisdn:'260973456049',failureReason:'INSUFFICIENT_BALANCE'},
    {code:'ZMB',country:'Zambia',mno:'AIRTEL_OAPI_ZMB',paymentType: 'DEPOSIT',msisdn:'260973456069',failureReason:'OTHER_ERROR'},
    {code:'ZMB',country:'Zambia',mno:'AIRTEL_OAPI_ZMB',paymentType: 'DEPOSIT',msisdn:'260973456129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'ZMB',country:'Zambia',mno:'AIRTEL_OAPI_ZMB',paymentType: 'DEPOSIT',msisdn:'260973456789',failureReason:'SUCCESS'},
    {code:'ZMB',country:'Zambia',mno:'AIRTEL_OAPI_ZMB',paymentType:'PAYOUT',msisdn:'260973456089',failureReason:'RECIPIENT_NOT_FOUND'},
    {code:'ZMB',country:'Zambia',mno:'AIRTEL_OAPI_ZMB',paymentType:'PAYOUT',msisdn:'260973456119',failureReason:'OTHER_ERROR'},
    {code:'ZMB',country:'Zambia',mno:'AIRTEL_OAPI_ZMB',paymentType:'PAYOUT',msisdn:'260973456129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'ZMB',country:'Zambia',mno:'AIRTEL_OAPI_ZMB',paymentType:'PAYOUT',msisdn:'260973456789',failureReason:'SUCCESS'},
    {code:'ZMB',country:'Zambia',mno:'MTN_MOMO_ZMB',paymentType: 'DEPOSIT',msisdn:'260763456019',failureReason:'PAYER_LIMIT_REACHED'},
    {code:'ZMB',country:'Zambia',mno:'MTN_MOMO_ZMB',paymentType: 'DEPOSIT',msisdn:'260763456029',failureReason:'PAYER_NOT_FOUND'},
    {code:'ZMB',country:'Zambia',mno:'MTN_MOMO_ZMB',paymentType: 'DEPOSIT',msisdn:'260763456039',failureReason:'PAYMENT_NOT_APPROVED'},
    {code:'ZMB',country:'Zambia',mno:'MTN_MOMO_ZMB',paymentType: 'DEPOSIT',msisdn:'260763456069',failureReason:'OTHER_ERROR'},
    {code:'ZMB',country:'Zambia',mno:'MTN_MOMO_ZMB',paymentType: 'DEPOSIT',msisdn:'260763456129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'ZMB',country:'Zambia',mno:'MTN_MOMO_ZMB',paymentType: 'DEPOSIT',msisdn:'260763456789',failureReason:'SUCCESS'},
    {code:'ZMB',country:'Zambia',mno:'MTN_MOMO_ZMB',paymentType:'PAYOUT',msisdn:'260763456079',failureReason:'RECIPIENT_NOT_FOUND'},
    {code:'ZMB',country:'Zambia',mno:'MTN_MOMO_ZMB',paymentType:'PAYOUT',msisdn:'260763456119',failureReason:'OTHER_ERROR'},
    {code:'ZMB',country:'Zambia',mno:'MTN_MOMO_ZMB',paymentType:'PAYOUT',msisdn:'260763456129',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'ZMB',country:'Zambia',mno:'MTN_MOMO_ZMB',paymentType:'PAYOUT',msisdn:'260763456789',failureReason:'SUCCESS'},
    {code:'ZMB',country:'Zambia',mno:'ZAMTEL_ZMB',paymentType: 'DEPOSIT',msisdn:'260953456704',failureReason:'INSUFFICIENT_BALANCE'},
    {code:'ZMB',country:'Zambia',mno:'ZAMTEL_ZMB',paymentType: 'DEPOSIT',msisdn:'260953456712',failureReason:'OTHER_ERROR'},
    {code:'ZMB',country:'Zambia',mno:'ZAMTEL_ZMB',paymentType: 'DEPOSIT',msisdn:'260953456789',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'ZMB',country:'Zambia',mno:'ZAMTEL_ZMB',paymentType: 'DEPOSIT',msisdn:'260953456700',failureReason:'SUCCESS'},
    {code:'ZMB',country:'Zambia',mno:'ZAMTEL_ZMB',paymentType:'PAYOUT',msisdn:'260953456712',failureReason:'OTHER_ERROR'},
    {code:'ZMB',country:'Zambia',mno:'ZAMTEL_ZMB',paymentType:'PAYOUT',msisdn:'260953456789',failureReason:'NO CALLBACK (stuck in SUBMITTED state)'},
    {code:'ZMB',country:'Zambia',mno:'ZAMTEL_ZMB',paymentType:'PAYOUT',msisdn:'260953456700',failureReason:'SUCCESS'}
];
export default function(country?: string | null,mno? : string | null ) {
    let output = msisdn;
    let output2: TestMsisdn[] = [];
    if (country){
                output = output.filter(c => c.country === country);
    }
    if (mno) {
                output2 = output.filter(c => c.mno === mno);
    }
    return output2.length > 0 ? output2 : output
}

export function GetUniqueCountries() {
    return msisdn.map((item: TestMsisdn) => item.country)
        .filter((value: any, index: number, self: any) => self.indexOf(value) === index);
}

export function GetUniqueMno(country? : string | null) {
    return msisdn.filter(c => c.country === country).map((item: TestMsisdn) => item.mno)
        .filter((value: any, index: number, self: any) => self.indexOf(value) === index);
}

export function getCountryFromCode(code: string | null) {
    if (code == null) return null;
    const c = msisdn.filter(c => c.code === code);
    return c.length > 0 ? c[0].country : null;
}

export function getCodeFromCountry(country: string) {
    const c = msisdn.filter(c => c.country === country);
    return c.length > 0 ? c[0].code : null;
}

